name: CheckStyle Test workflow

on: 
  push:
    branches: gh-pages

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
